export const PortfolioData = [
  {
    id: 1,
    category: "Games",
    title: "2D Narrative",
    image: require("./Images/narrative sc.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 2,
    category: "Websites",
    title: "NASA APOD Website ",
    image: require("./Images/apod site.png"),
    github: "https://sihle-mazibuko.github.io/Data-Visualization/",
  },
  {
    id: 3,
    category: "Games",
    title: "Blind Bomber",
    image: require("./Images/BOMBER SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 4,
    category: "Games",
    title: "Bullet Hell",
    image: require("./Images/BulletHell.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 5,
    category: "Games",
    title: "StreetFight",
    image: require("./Images/chefsc.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 6,
    category: "Games",
    title: "Dungeon Crawler",
    image: require("./Images/DCRAWL SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 7,
    category: "Assets",
    title: "Donut",
    image: require("./Images/DONUT.png"),
    github: "https://github.com/Sihle-jpeg/Assets",
  },
  {
    id: 8,
    category: "Developments",
    title: "Recipe WebApp Prototype",
    image: require("./Images/eats sc.png"),
    github: "https://github.com/Sihle-Mazibuko/Recipe-App",
  },
  {
    id: 9,
    category: "Games",
    title: "ETG Clone",
    image: require("./Images/ETG SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 10,
    category: "Assets",
    title: "AR Blend",
    image: require("./Images/AR BLEND.png"),
    github: "https://github.com/Sihle-jpeg/Assets",
  },
  {
    id: 11,
    category: "Games",
    title: "Earth Clicker",
    image: require("./Images/LIFE SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 12,
    category: "Websites",
    title: "Music Site",
    image: require("./Images/music site.png"),
    github: "https://sihle-mazibuko.github.io/Single-Page-App/",
  },
  {
    id: 13,
    category: "Assets",
    title: "Pistol",
    image: require("./Images/Pistol.png"),
    github: "https://github.com/Sihle-jpeg/Assets",
  },
  {
    id: 14,
    category: "Games",
    title: "Platformer",
    image: require("./Images/plat.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 15,
    category: "Websites",
    title: "Original Portfolio Site",
    image: require("./Images/portfolio site.png"),
    github: "https://sihle-mazibuko.github.io/Portfolio/",
  },
  {
    id: 16,
    category: "Assets",
    title: "Character Rig (Blambino)",
    image: require("./Images/Rig blambo.png"),
    github: "https://github.com/Sihle-jpeg/Assets",
  },
  {
    id: 17,
    category: "Games",
    title: "Blambino 2",
    image: require("./Images/Shooter.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 18,
    category: "Games",
    title: "Solitaire",
    image: require("./Images/SOLITAIRE SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 19,
    category: "Games",
    title: "Stick Game Clone",
    image: require("./Images/STICK GAME SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 20,
    category: "Games",
    title: "RPG Prototype",
    image: require("./Images/TD RPG SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 21,
    category: "Games",
    title: "The Life of Fly",
    image: require("./Images/TLOF SC.png"),
    github: "https://github.com/Sihle-jpeg/Games",
  },
  {
    id: 22,
    category: "Assets",
    title: "Alien Blend",
    image: require("./Images/UV SC.png"),
    github: "https://github.com/Sihle-jpeg/Assets",
  },
];

export const projectsNav = [
  {
    name: "all",
  },
  {
    name: "Games",
  },
  {
    name: "Developments",
  },
  {
    name: "Websites",
  },
  {
    name: "Assets",
  },
];
